precision: bf16-true
resume: false
train:
  save_interval: 20000
  log_interval: 1
  epochs: 1
  max_steps:
  max_seq_length: 512
eval:
  interval: 25000
  initial_validation: false
  final_validation: false
logger_name: csv